### ISSUE TITLE
Design About Page

### ISSUE THREAD

**Issue by nbuonin** [nbuonin/tcs-prototype#12]
This page will include: 
- About Us
- History
- How We Work
- Board
- Officers
- Staff

**Comment by alicebemusing** [comment]
We need this full text from someone else before I can lay this out...

**Comment by nbuonin** [comment]
Done by @alicebemusing: http://nbuonin.github.io/tcs-prototype/about.html

**Comment by nbuonin** [comment]
Done by @alicebemusing: http://nbuonin.github.io/tcs-prototype/about.html
